[package]
name = "tests"
version = "0.1.0"
authors = ["Ben Porebski <ben@inoxx.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
ndarray = "0.15.4"